# Generated by Django 3.2.3 on 2023-10-26 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('year_book', '0003_auto_20231026_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='post',
            field=models.CharField(help_text='Designation of the member eg CEO', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 14, 26, 49, 711636), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 14, 26, 49, 711636), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='year_book',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 14, 26, 49, 711636), verbose_name='date uploaded'),
        ),
    ]
