# Generated by Django 3.2.3 on 2023-10-26 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('year_book', '0004_auto_20231026_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 14, 28, 53, 440011), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 14, 28, 53, 440011), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='year_book',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 14, 28, 53, 455625), verbose_name='date uploaded'),
        ),
    ]
