# Generated by Django 3.2.3 on 2023-10-26 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('year_book', '0007_auto_20231026_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 58, 10, 702843), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 58, 10, 702843), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='year_book',
            name='facebook_handle',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='year_book',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='year_book',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='year_book',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 22, 58, 10, 718464), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='year_book',
            name='twitter_handle',
            field=models.URLField(blank=True),
        ),
    ]
