# Generated by Django 3.2.3 on 2023-10-30 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('year_book', '0010_auto_20231027_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='year_book',
            name='resident_address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 6, 20, 3, 127589), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 6, 20, 3, 127589), verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='year_book',
            name='time_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 6, 20, 3, 127589), verbose_name='date uploaded'),
        ),
    ]
